name: hand_by_hand_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  meta: ^1.15.0
  equatable: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  dotted_border: ^2.1.0
  multi_select_flutter: ^4.1.3
  image_picker: ^1.1.2
  dartz: ^0.10.1
  focused_menu: ^1.0.5
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_nav_bar: ^5.0.6
  readmore: ^3.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/category/
